name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code
        uses: golangci/golangci-lint-action@v2
        with:
          args: ['run', '-v']

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          platforms: ${{ matrix.platform }}
          tags: tobai/sdx6ue_1:${{ matrix.platform }}

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Scan Docker Image
        run: docker run --rm aquasec/trivy tobai/sdx6ue_1:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongodb:
        image: mongo:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Wait for MongoDB
        run: docker-compose exec -T mongodb mongo --eval "printjson(db.serverStatus())" > /dev/null
      - name: Test Application
        run: |
          curl -X POST http://localhost:8080/recipes \
            -H "Content-Type: application/json" \
            -d '{"name": "Test Recipe", "description": "This is a test recipe."}'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tobai/sdx6ue_1:latest
